language: cpp

before_install:
  - |-

before_cache:
  - |-

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
    - os: osx

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake -DULOG_BUILD_TESTS=ON ../ && cmake --build ./ --target ulog_test && ls -al
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then ./tests/ulog_test; fi
